### ISSUE TITLE
jupyter notebook kernel died when import netket

### ISSUE THREAD

**Issue by ericntunctu** [netket/netket#322]
I have already checked that I installed netket successfully, at least there is no error shows up.
I am using the Ubuntu subsystem in the windows and create a virtual environment and install python packages and netket by using. 

$ python3 -m pip install cmake
$ python3 -m pip install --index-url https://test.pypi.org/simple/ netket

Other python packages (CMake) already installed.
I still do not know the reason.
![Capture](https://user-images.githubusercontent.com/35599752/70552220-edd45e00-1b46-11ea-8150-401917608405.PNG)

**Comment by gcarleo** [comment]
hi, thanks for reporting this. 
Can I ask you why you are install netket from test.pypi? do you have issues with pip3 install netket? (i.e. not from the test.pypy repo). 

In any case, this looks like an issue with MPI on your installation. This is a bit tricky to get right with conda environments. Can you just run one of the examples (in the /Examples/ folder) from the command line without using a notebook?

**Comment by ericntunctu** [comment]
There is an error happend when I use pip3 install netket. So I just it to by using test.pypy repo and then it looks ok. (After I run pip3 install netket. There is no error reported. )

It's strange that I can only find two files about netket in the python packages.
![image](https://user-images.githubusercontent.com/35599752/70557689-4dd00200-1b51-11ea-9c61-cbdef3e9c2d2.png)

Thanks

**Comment by gcarleo** [comment]
what error do you get when you do pip install netket from the main repo?

**Comment by ericntunctu** [comment]
![0 2](https://user-images.githubusercontent.com/35599752/70559455-a81e9200-1b54-11ea-9f29-2cf47fa35243.PNG)



![01](https://user-images.githubusercontent.com/35599752/70559456-a81e9200-1b54-11ea-9419-b7fe30e0f39a.PNG)

**Comment by gcarleo** [comment]
As you can see from the error messages, in the first case you don't have permissions to install it (using a python environment should solve this), in the second case instead it says that the cmake version you have is not new enough

**Comment by ericntunctu** [comment]
Ok, thanks, after I get the cmake and run pip install netket, I still get the following: 
![Capture](https://user-images.githubusercontent.com/35599752/70566161-88419b00-1b61-11ea-8daa-9f84b734530b.PNG)
![Capture1](https://user-images.githubusercontent.com/35599752/70566162-88419b00-1b61-11ea-8129-84ae95a887b9.PNG)

thanks for you keeping help me

**Comment by gcarleo** [comment]
This shouldn't happen with the last version registered on pip though. Are you sure you are trying to install the 2.0.1 version?

**Comment by ericntunctu** [comment]
Sorry? Which one should be 2.0.1 version?

**Comment by ericntunctu** [comment]
I just run pip install netket

**Comment by ericntunctu** [comment]
Thanks, I solved the problem by dealing with BLAS library. Now I already finished the installing and playing with the examples.
